### ISSUE TITLE
Schema validation warning

### ISSUE THREAD

**Issue by henrycosta05** [MichaelBarney/Dialogflow-Twilio-Whatsapp-Conector#4]
Boa tarde pessoal,
realizei o passo-a-passo ontem e estou recebendo este erro ao utilizar o sandbox, alguém passou por isso?
```

Warning - 12200
Schema validation warning
The provided XML does not conform to the Twilio Markup XML schema. Please refer to the specific error and correct the problem.
```

**Comment by MichaelBarney** [comment]
Oi Henry! Outra pessoa teve este mesmo erro antes, analisamos juntos mas não encontramos problemas no conector. Ele refez o passo a passo do 0 e conseguiu parar de receber o alerta, mas não descobrimos o motivo

**Comment by henrycosta05** [comment]
tá certo, obrigado @MichaelBarney. Vou refazer o processo aqui, se eu encontrar algo vou postar aqui.
