### ISSUE TITLE
Schema Validation Warning

### ISSUE THREAD

**Issue by gspalmeida** [MichaelBarney/Dialogflow-Twilio-Whatsapp-Conector#5]
Looking to the TwillioDashboard I found this "12200 - Schema Validation Warning" notification.

Screenshots from the Twillio debugger: (I removed the personal account data)

![image](https://user-images.githubusercontent.com/47248432/113710220-d022f480-96b9-11eb-895b-e75f0bf63e3b.png)

![image](https://user-images.githubusercontent.com/47248432/113710425-0e201880-96ba-11eb-8e15-8cada93e964c.png)

![image](https://user-images.githubusercontent.com/47248432/113710454-1b3d0780-96ba-11eb-86a9-c896fbaf3ffe.png)

**Comment by gspalmeida** [comment]
I would like to solve this, but I cant figure out what is wrong in the connector script

**Comment by danishVF** [comment]
@gspalmeida I am stuck at creating the function. I am getting "failed to deploy" error on console.cloud.google.com under my chatbot project. I'll appreciate if you could help regarding that. Thanks

**Comment by gspalmeida** [comment]
> @gspalmeida I am stuck at creating the function. I am getting "failed to deploy" error on console.cloud.google.com under my chatbot project. I'll appreciate if you could help regarding that. Thanks

I believe that the error you are facing isn't related to the issue reported. And if we start to talk about it here, will be a messy kkkkk.

So I suggest you to create another issue with the proper information about your problem, and than we talk about there. 

PS: Please tag me in your new issue (@gspalmeida ), and I will try to help you.

**Comment by gspalmeida** [comment]
> > @gspalmeida I am stuck at creating the function. I am getting "failed to deploy" error on console.cloud.google.com under my chatbot project. I'll appreciate if you could help regarding that. Thanks
> 
> I believe that the error you are facing isn't related to the issue reported. And if we start to talk about it here, will be a messy kkkkk.
> 
> So I suggest you to create another issue with the proper information about your problem, and than we talk about there.
> 
> PS: Please tag me in your new issue (@gspalmeida ), and I will try to help you.

@danishVF  In fact I already forked your question to another issue, so please decribe your inviroment there ^^

PS: If you are Brazilian, or fell more confortable giving details in Portuguese, its good for me too (Because my nature laguage is portuguese).

PS²: If you dont know Portuguese, just ignore the "PS:" kkkkkkkkk

**Comment by gspalmeida** [comment]
> Looking to the TwillioDashboard I found this "12200 - Schema Validation Warning" notification.
> 
> Screenshots from the Twillio debugger: (I removed the personal account data)
> 
> ![image](https://user-images.githubusercontent.com/47248432/113710220-d022f480-96b9-11eb-895b-e75f0bf63e3b.png)
> 
> ![image](https://user-images.githubusercontent.com/47248432/113710425-0e201880-96ba-11eb-8e15-8cada93e964c.png)
> 
> ![image](https://user-images.githubusercontent.com/47248432/113710454-1b3d0780-96ba-11eb-86a9-c896fbaf3ffe.png)

@MichaelBarney Do you have any ideas about why we get this warning on every message?

**Comment by MichaelBarney** [comment]
Analisei aqui o problema e vi que agora precisa ativar uma API para funcionar, segue o link. Me avisa se funcionar:

É necessário ativar a API do Cloud Build,  ative ela aqui: https://console.cloud.google.com/marketplace/product/google/cloudbuild.googleapis.com

**Comment by DanielLCintra** [comment]
Eu já tinha ativado a api e mesmo assim recebi o erro...

**Comment by DanielLCintra** [comment]
A solução é substituir o conteúdo da linha 76 por isso aqui: 
`response.status(200).send("<Response><Message>Sent!</Message></Response>");`

o original era:
`response.status(200).send("Sent!");`

**Comment by MichaelBarney** [comment]
Hi Guys! Just updated the codebase in order to fix many problems that appeared during the first year of this integration. With many changes in how twilio and cloud functions worked, the best and most secure solution was to use Twilio Functions instead of cloud functions.

**Comment by gspalmeida** [comment]
> A solução é substituir o conteúdo da linha 76 por isso aqui:
> `response.status(200).send("<Response><Message>Sent!</Message></Response>");`
> 
> o original era:
> `response.status(200).send("Sent!");`

Opa, mto obrigado, era isso mesmo... Essa alteração é pra a resposta se adequar ao twiml né?
