### ISSUE TITLE
Hard Times Deploying the function to google.cloud

### ISSUE THREAD

**Issue by gspalmeida** [MichaelBarney/Dialogflow-Twilio-Whatsapp-Conector#6]
@gspalmeida I am stuck at creating the function. I am getting "failed to deploy" error on console.cloud.google.com under my chatbot project. I'll appreciate if you could help regarding that. Thanks

_Originally posted by @danishVF in https://github.com/MichaelBarney/Dialogflow-Twilio-Whatsapp-Conector/issues/5#issuecomment-817907180_

**Comment by MichaelBarney** [comment]
Vem conversar comigo pelo telegram, no comentário em destaque dos vídeos tem o link, aí posso te ajudar melhor

**Comment by danishVF** [comment]
@MichaelBarney Eu usei o Google Translate para este comentário, então, por favor, não julgue minhas habilidades no idioma português
1 - Não encontrei seu telegrama em lugar nenhum, agradeço se você puder me fornecer isso.
2 - Além dos vídeos que você mencionou, também não sei onde encontrá-los. Ou eles estão explicando as etapas neste repo?
3 - Não encontrei a opção de seguir a etapa de criação de uma nova função de nuvem:
                  Step 7 - Set the Function to Execute field to "TwilioWebhook"
                  
![image](https://user-images.githubusercontent.com/72489412/114795239-8b791680-9da7-11eb-913f-5f7570860aa7.png)

4 - Also for "Step 9 - In the Enviroment Variables section, look for Runtime Envir:oment Variables and click on "Add Variable"
              I didn't find fields for "projectId", "accountSid", & "authToken" 
              
              
![image](https://user-images.githubusercontent.com/72489412/114795330-b8c5c480-9da7-11eb-99f2-1bbfe05867e6.png)
